### ISSUE TITLE
support for `if`, `then`, `else` schemas

### ISSUE THREAD

**Issue by elmerbulthuis** [LuvDaSun/JsonSchema42#24]
implement it!

**Comment by elmerbulthuis** [comment]
This could be done by transforming the `if`, `then`, `else` into a `oneOf` with an `allOf` of the `if` and `then` type and another `allOf` with the `then` and a `not` type with the `then` type.

So something like this:
```yaml
if:
  id: if
then:
  id: then
else:
  id: else
```
will become
```yaml
oneOf
- allOf
  - id: if
  - id: then
- allOf
  - not:
      id: if
  - id: else
```
ofcourse we first need to support the not type, see #23 .
